In [1]:
#Numpy Practice Session 1
import numpy as np

#What is an ARRAY
An array is a central data structure of the NumPy library. An array is a grid of values and it containsinformation about the raw data

In [40]:
arr_1=np.array([[[[1,2,3,4],[5,6,7,8],[9,11,11,12],[13,14,15,16]],
                 [[17,18,19,20],[21,22,23,24],[25,26,27,28],[29,30,31,32]],
                 [[1,2,3,4],[5,6,7,8],[9,11,11,12],[13,14,15,16]],
                 [[17,18,19,20],[21,22,23,24],[25,26,27,28],[29,30,31,32]]]])
arr_1

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 11, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 11, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]]]])

In [43]:
arr_1.ndim

4

In [44]:
#We use sqeeze function to reduce the 
#numpy.squeeze() removes dimensions that have size = 1
arr_1.squeeze()

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 11, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 11, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [42]:
#To find the shape of the matrix
np.shape(arr_1)

(1, 4, 4, 4)

In [46]:
#To find the dimension of the matrix
arr_1.ndim

4

In [15]:
print(arr_1[0][0])
print(arr_1[0][0])
print(arr_1[0][0])
print(arr_1[0][0])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [16]:
print(arr_1[0][0])
print(arr_1[0][1])
print(arr_1[0][2])
print(arr_1[0][3])

[1 2 3 4]
[5 6 7 8]
[ 9 11 11 12]
[13 14 15 16]


In [21]:
for i in enumerate(arr_1):
    print(i)

(0, array([1, 2, 3, 4]))
(1, array([5, 6, 7, 8]))
(2, array([ 9, 11, 11, 12]))
(3, array([13, 14, 15, 16]))


In [47]:
a=arr_1 #Changing the variable name to a

In [48]:
a

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 11, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 11, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]]]])

In [65]:
#Printing an element from a 4D array
a[0][3][3][2]

np.int64(31)

In [66]:
a= np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])

In [67]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
print(a[0][0])

1


***Dimensions= Axes**

In [71]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [77]:
#2 indixes can be given for 2D  array only

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [81]:
#Creating an array woith Zeros
z= np.zeros([3,4], dtype=int)

In [82]:
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [83]:
#Creating an array with ones
o=np.ones([5,6], dtype=int)

In [84]:
o

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [85]:
#we use empty function, when we want to update values immediately
#np.empty() = uninitialized memory
#Values look random because they are leftover data
e= np.empty(3)

In [86]:
e

array([ 1.00912434e-311,  0.00000000e+000, -6.47591605e-319])

In [87]:
e[0]=10

In [88]:
e

array([ 1.0000e+001,  0.0000e+000, -6.4759e-319])

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1795887.py, line 1)

In [93]:
#Creating an array woith a range of elements
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
#Using Start, Stop and Step in Arange Function
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [116]:
# we can use linspace() function which gives values which are spaced linearly in equal intervals
l=np.linspace(10,30,3, retstep=False,
    dtype=int)

In [117]:
l

array([10, 20, 30])

***Adding, removing and  sorting elements
argsort, which is an indirect sort along a specified axis,
lexsort, which is an indirect stable sort on multiple keys,
searchsorted, which will find elements in a sorted array, and
partition, which is a partial sort***

In [121]:
#TO join 2 arrays with concatenate
b=np.array([1,2,3,4])
c=np.array([5,6,7,8])
d=np.concatenate((b,c))
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
z1=np.concatenate((x,y),axis=0)
z1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
#we can only concatenate same dimensions for concatenate method
np.ndim(y)

1

In [133]:
#If we  wan to remove an element from the array
arr=np.array([10,20,30,40])
new_arr=np.delete(arr, 2)

In [134]:
new_arr

array([10, 20, 40])

In [135]:
z1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [136]:
#If we wantto remove a row from the array
np.delete(z1,2,axis=0)

array([[1, 2],
       [3, 4]])

In [138]:
z1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [140]:
#To fi d the total number of elements present in the array
z1.size

6

In [141]:
z1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [142]:
z1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [163]:
#sorting a set of randomly generated elements in a particular range
f=np.sort((np.random.randint(2,20,13)))
f

array([ 4,  5,  5,  7,  8,  9,  9, 11, 12, 15, 15, 16, 18], dtype=int32)

In [164]:
#Selecting arrays with conditios
a=np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150])
a


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [165]:
print(a[a>=50])


[ 50  60  70  80  90 100 110 120 130 140 150]


In [169]:
div2=a[a%4==0]
print(div2)

[ 20  40  60  80 100 120 140]


In [171]:
c=a[(a>=20)&(a<=90)]

In [175]:
d=a[(a>=50)|(a<=50)]
d

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [176]:
not_there=np.nonzero(a==45)

In [177]:
print(not_there)

(array([], dtype=int64),)


***Creating an array from existing data***

In [178]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [180]:
arr1=a[3:8]

In [181]:
arr1

array([4, 5, 6, 7])

In [183]:
#Stacking the arrays with same dimeension vertically
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a3=np.vstack((a1,a2))

In [184]:
a3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [185]:
#Stacking the arrays with same dimeension horizontally
a4=np.hstack((a1,a2))


In [186]:
a4

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [187]:
#using arange and reshape in one query
x=np.arange(1,30,2).reshape(3,5)

In [188]:
x

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [189]:
np.hsplit(x,3)

ValueError: array split does not result in an equal division

In [190]:
#Array Addition 
data=np.array([1,2,3])
ones=np.ones((1,1,1))

In [191]:
data=data+ones

In [192]:
data

array([[[2., 3., 4.]]])

In [193]:
data.sum()

np.float64(9.0)

In [ ]:
#axis=0 → compare vertical values
#axis=1 → compare horizontal values