In [41]:
#numppy is numerical python
import numpy as np

In [2]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [3]:
np.__version__

'2.3.5'

In [4]:
my_list=[0,1,2,3,4,5]
type(my_list)

list

In [5]:
array=np.array(my_list)

In [10]:
array

array([0, 1, 2, 3, 4, 5])

In [11]:
type(array)

numpy.ndarray

In [12]:
#arange give the values in array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(0,20,25)

array([0])

In [18]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
#1st argument should always be less than 2nd argument
np.arange(20,8)

array([], dtype=int64)

In [20]:
np.arange(-20,8) #1st arg < 2nd arg 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [21]:
#array with zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [28]:
#Zeros matrix with nd
np.zeros([7,10], dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
#ones matrix with nd
np.ones([4,5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.ones([10,10],dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [38]:
np.three(3,3)

AttributeError: module 'numpy' has no attribute 'three'

In [40]:
nd1=np.ones([10,10], dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [42]:
rand(3,2)

NameError: name 'rand' is not defined

In [44]:
#Rand(Rows, columns)
np.random.rand(3,6)

array([[0.50191707, 0.43938691, 0.28758361, 0.2599804 , 0.91081727,
        0.77373927],
       [0.3556687 , 0.37282854, 0.00594892, 0.53895419, 0.28376095,
        0.23208651],
       [0.28382128, 0.27105358, 0.06726947, 0.49300824, 0.34805579,
        0.81813731]])

In [51]:
np.random.randint(6)

3

In [60]:
#gENERATE 7 RANDOM NUMBERS BETWEEN 2 AND 10 AND 10 IS EXCLUESIVE
np.random.randint(2,10,7)

array([7, 5, 3, 5, 3, 6, 4], dtype=int32)

In [62]:
np.random.randint(3,5)

3

In [63]:
np.random.randint(2,10,5)

array([7, 2, 5, 9, 4], dtype=int32)

In [64]:
np.random.randint(10,40,(10,10))

array([[14, 30, 23, 35, 29, 15, 16, 33, 38, 28],
       [12, 16, 23, 23, 11, 19, 36, 34, 38, 22],
       [24, 31, 28, 28, 22, 34, 19, 15, 11, 34],
       [36, 26, 28, 38, 22, 16, 29, 25, 26, 36],
       [17, 27, 39, 17, 39, 13, 26, 34, 23, 11],
       [23, 12, 28, 28, 18, 36, 39, 27, 37, 17],
       [25, 17, 25, 20, 30, 30, 29, 38, 11, 15],
       [27, 12, 39, 26, 21, 11, 10, 28, 18, 28],
       [35, 20, 34, 19, 13, 20, 34, 33, 22, 33],
       [36, 17, 37, 18, 39, 16, 26, 14, 27, 35]], dtype=int32)

In [66]:
arr=np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [67]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
#here it is printting the values between 10 to 19 in 5 rows and 4 columns and then we are storing the the values in m
m=np.random.randint(10,40,(5,4))

In [71]:
m

array([[34, 23, 35, 10],
       [37, 23, 30, 36],
       [24, 10, 10, 28],
       [20, 34, 13, 26],
       [19, 15, 17, 13]], dtype=int32)

In [76]:
m[0:4:2]

array([[34, 23, 35, 10],
       [24, 10, 10, 28]], dtype=int32)

In [77]:
m[1:-2]

array([[37, 23, 30, 36],
       [24, 10, 10, 28]], dtype=int32)

In [80]:
print(m[2,3])

28


In [81]:
m

array([[34, 23, 35, 10],
       [37, 23, 30, 36],
       [24, 10, 10, 28],
       [20, 34, 13, 26],
       [19, 15, 17, 13]], dtype=int32)

#Slicing

In [82]:
b=np.random.randint(10,30,(5,6))

In [83]:
b

array([[20, 16, 17, 14, 19, 16],
       [17, 22, 18, 15, 21, 18],
       [10, 28, 15, 18, 13, 13],
       [14, 17, 11, 10, 27, 12],
       [14, 13, 29, 11, 14, 17]], dtype=int32)

In [84]:
b[:]

array([[20, 16, 17, 14, 19, 16],
       [17, 22, 18, 15, 21, 18],
       [10, 28, 15, 18, 13, 13],
       [14, 17, 11, 10, 27, 12],
       [14, 13, 29, 11, 14, 17]], dtype=int32)

In [85]:
b[2,3]

np.int32(18)

In [89]:
b[1:4]

array([[17, 22, 18, 15, 21, 18],
       [10, 28, 15, 18, 13, 13],
       [14, 17, 11, 10, 27, 12]], dtype=int32)

In [91]:
b[-1::]

array([[14, 13, 29, 11, 14, 17]], dtype=int32)

In [92]:
b[:-4]

array([[20, 16, 17, 14, 19, 16]], dtype=int32)

In [93]:
b

array([[20, 16, 17, 14, 19, 16],
       [17, 22, 18, 15, 21, 18],
       [10, 28, 15, 18, 13, 13],
       [14, 17, 11, 10, 27, 12],
       [14, 13, 29, 11, 14, 17]], dtype=int32)

In [100]:
b[:-2]

array([[20, 16, 17, 14, 19, 16],
       [17, 22, 18, 15, 21, 18],
       [10, 28, 15, 18, 13, 13]], dtype=int32)

In [102]:
b[-4:-2]

array([[17, 22, 18, 15, 21, 18],
       [10, 28, 15, 18, 13, 13]], dtype=int32)

In [104]:
b[3,4]

np.int32(27)

In [105]:
b[3,-2]

np.int32(27)

In [106]:
arr

array([0, 1, 2, 3, 4, 5])

In [107]:
arr.max()

np.int64(5)

In [108]:
arr.min()

np.int64(0)

In [109]:
from numpy import *

In [110]:
mean(arr)

np.float64(2.5)

In [111]:
arr

array([0, 1, 2, 3, 4, 5])

In [112]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [113]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [115]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [117]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [118]:
#TO print the column elements
b[:,3]

array([14, 15, 18, 10, 11], dtype=int32)

In [119]:
#It prints all the elements from 3rd column
b

array([[20, 16, 17, 14, 19, 16],
       [17, 22, 18, 15, 21, 18],
       [10, 28, 15, 18, 13, 13],
       [14, 17, 11, 10, 27, 12],
       [14, 13, 29, 11, 14, 17]], dtype=int32)

In [120]:
arr

array([0, 1, 2, 3, 4, 5])

In [121]:
b

array([[20, 16, 17, 14, 19, 16],
       [17, 22, 18, 15, 21, 18],
       [10, 28, 15, 18, 13, 13],
       [14, 17, 11, 10, 27, 12],
       [14, 13, 29, 11, 14, 17]], dtype=int32)

In [122]:
#It gives reverse of the code with step 1
b[::-1]

array([[14, 13, 29, 11, 14, 17],
       [14, 17, 11, 10, 27, 12],
       [10, 28, 15, 18, 13, 13],
       [17, 22, 18, 15, 21, 18],
       [20, 16, 17, 14, 19, 16]], dtype=int32)

In [123]:
#It gives reverse of the code with step 2- Eery alternative row is pprinted
b[::-2]

array([[14, 13, 29, 11, 14, 17],
       [10, 28, 15, 18, 13, 13],
       [20, 16, 17, 14, 19, 16]], dtype=int32)

In [124]:
c=np.random.randint(10,100,(10,10))

In [125]:
c

array([[96, 96, 91, 86, 75, 78, 37, 92, 28, 12],
       [26, 23, 81, 81, 67, 40, 11, 71, 46, 55],
       [39, 48, 36, 94, 97, 86, 34, 71, 24, 50],
       [84, 10, 95, 72, 53, 95, 42, 25, 38, 29],
       [44, 60, 78, 59, 58, 71, 75, 43, 52, 27],
       [67, 49, 67, 32, 98, 89, 36, 14, 23, 52],
       [62, 96, 79, 40, 45, 59, 21, 10, 93, 96],
       [89, 63, 47, 17, 75, 53, 96, 83, 16, 76],
       [99, 11, 17, 82, 93, 17, 34, 11, 79, 79],
       [25, 34, 91, 43, 67, 61, 62, 12, 84, 46]], dtype=int32)

In [126]:
c[::-3]

array([[25, 34, 91, 43, 67, 61, 62, 12, 84, 46],
       [62, 96, 79, 40, 45, 59, 21, 10, 93, 96],
       [84, 10, 95, 72, 53, 95, 42, 25, 38, 29],
       [96, 96, 91, 86, 75, 78, 37, 92, 28, 12]], dtype=int32)

In [129]:
#To print a small matrix from inside the whole matrix
c[3:7,2:6]

array([[95, 72, 53, 95],
       [78, 59, 58, 71],
       [67, 32, 98, 89],
       [79, 40, 45, 59]], dtype=int32)

In [134]:
#Masking ork Filter
c[c>=50]

array([96, 96, 91, 86, 75, 78, 92, 81, 81, 67, 71, 55, 94, 97, 86, 71, 50,
       84, 95, 72, 53, 95, 60, 78, 59, 58, 71, 75, 52, 67, 67, 98, 89, 52,
       62, 96, 79, 59, 93, 96, 89, 63, 75, 53, 96, 83, 76, 99, 82, 93, 79,
       79, 91, 67, 61, 62, 84], dtype=int32)